### ISSUE TITLE
Can't scrape Response Time, Membership and Amenities

### ISSUE THREAD

**Issue by Atch90** [hamelsmu/AirbnbScrape#7]
Hi !

First of all thank you very much for your work, it's really great and helpful !

I have noticed the following errors for each listing that I try to scrape:

Unable to parse response time for listing id: [...]
Unable to parse membership date for listing id: [...]
Error in getting amenities for listing iD: [...]

I am using the latest version of AirbnbScrape.py; maybe there is some new change in the web pages?

Best Regards,

Atch

**Comment by mozboz** [comment]
Have you seen this PR? It might fix some issues

https://github.com/hamelsmu/AirbnbScrape/pull/5

**Comment by Atch90** [comment]
Hi !

sorry, i am pretty new at this and i thought that the fixes were in the latest version. I have applied the fixes suggested in the PR and now it works. 

Thank you very much !
